apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dispatcher_deployment.yaml
  - dispatcher_service.yaml

#génération d'une configmap managé par Kustomize à partir d'application.yaml
configMapGenerator:
  - name: dispatcher-config #base du nom de la CM générée
    files:
      - application.yaml
    options:
      labels:
        app: dispatcher-service